### ISSUE TITLE
Not working for Windows 10?

### ISSUE THREAD

**Issue by pinguluk** [dongido001/vscode-sync-env#13]
The destination files are not changing. Using Windows 10.

**Comment by dongido001** [comment]
Hi, thanks for filling this. 

~~Unfortunately, I can confirm the issue as I can;t get a windows 10 PC handy currently...~~

~~I will try to investigate when I have one in handy.~~

~~for now, PR are welcome from anyone that wants to fix!~~

Trying it out today, thanks!

**Comment by dongido001** [comment]
fixed by #20

**Comment by dongido001** [comment]
checkout version 1.0.7
