### ISSUE TITLE
Bug: Sync Issue with value with =

### ISSUE THREAD

**Issue by mbalandis** [dongido001/vscode-sync-env#22]
Thanks for creating this extension. Really useful.

For a while the extension worked great however I have encountered a bug. It is a niche but bug nonetheless. I have a specific situation where this value is needed.

This happens when the value of the env has = in it so if I have example:
`FOOBAR="-foo=bar"` 
and .env doesn't have this value yet it works fine. It simply adds:
`FOOBAR=`

but let's say I want to have this value in example so at the point so I have value in .env and .env.example:
`FOOBAR="-foo=bar"`

then next time I save .env and it syncs it returns:
`FOOBAR="-foo` 

removes " and messes up all other that are after. Tried with "" and without, same issue.

So my solution would be not to check just after = per line but to check after first = per line. Not sure how exactly it is coded but that prolly would be a solution. 

Note: I tried https://github.com/DrummerSi/vscode-sync-env to test has same issue. There is another extension but it doesn't keep the values. So I would still want to consider using yours so if you could have a fix, would be great! :)

If you have questions, let me know.

**Comment by dongido001** [comment]
Hey @mbalandis,

Thanks for discovering this bug and clear reproduction steps. This is now fixed and released in v1.0.8.

You can now update the extension.
