### ISSUE TITLE
Persist inline comments

### ISSUE THREAD

**Issue by jd-solanki** [dongido001/vscode-sync-env#23]
Hi 👋🏻 

Thanks for creating this extion. This is super useful and still I don't know why people aren't using it.

After using it for certain period I realized I need one more feature from it which I think is we can consider as bug and feature req.

Right now, If I've some optional .env property then I like to do something like this in my `.env` file:
```env
ENVIRONMENT= # optional
HASH_SECRET_KEY=secret
```

Which should result in following `.env.example` file:
```env
ENVIRONMENT= # optional
HASH_SECRET_KEY=
```

However, It generates `.env.example` like below:
```env
ENVIRONMENT=
HASH_SECRET_KEY=
```

So, can we make inline comments persist for adding comments?

---

**Alternative:** Why not comment above the line? This is because we already have groups via new line comment and adding comments for meta details like optional on new line will make it less readable.
![image](https://github.com/user-attachments/assets/210ac7e9-715d-4bb7-a660-4f789dc6143a)

**Comment by dongido001** [comment]
Oh nice! sorry, for the late reply. I just got to see this issue now. I love the alternative method, as the inline comment may interfere with some other intention.

For example, one might have its config as:

PASS=RANDOM#$%$##

and it will result in the .env.example as:

PASS=#$%$##

The alternate method currently works like that I guess.

**Comment by jd-solanki** [comment]
I'll write comments above the env variable. No worries, Thanks for the response.
