### ISSUE TITLE
Add option for custom example file

### ISSUE THREAD

**Issue by muuvmuuv** [dongido001/vscode-sync-env#8]
I would like to name my `.env.example` to `.env.default`. Because for me and in all my projects, the `.env` file is never an example more a requirement for some API to work. Can you add this option?

**Comment by dongido001** [comment]
Yeah. I can make this work by introducing a setting file where the files name can be set.

Thanks for openinng this, I will be working on it...

**Comment by GorvGoyl** [comment]
would be nice to have an option to configure the base .env file instead of .env.example.. I'm using https://www.npmjs.com/package/dotenv-flow package and I'm maintaining one base .env file and all other .env.local, .env.prod etc files are overriding thisfile.

**Comment by dongido001** [comment]
OK, cool

**Comment by dongido001** [comment]
This is now added on 1.0.5: https://github.com/dongido001/vscode-sync-env#configuring-sync-files
